#######################################################################
### CXX: The name of the c++ compiler
### CC : The name of the c   compiler
### F77: The name of the Fortran 77 compiler
### F77FLAGS: Flags which are needed by the Fortran compiler
### ROOTDIR: The installation directory of the tool
CXX = g++
CC  = gcc
F77 = g77
F77FLAGS = -fno-underscoring
LINK = "-lf2c"
INCL ="-I/usr/local/include"
CFLAGS =#
ROOTDIR = /home/sheridan/QtProjects/GenConstraint/
